package revature.Day4;

import java.io.IOException;

/**
 * to demonstrate that we can throw multiple exception at the same time
 * also used key word throws
 */
class Calulator{

    public void test() throws ArithmeticException, NullPointerException, IOException {

    }

}

public class Demo7 {
    public static void main(String[] args) {

    }
}

